/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Advertise: typeof import('./src/components/modals/advertise.vue')['default']
    AdvertiseTask: typeof import('./src/components/advertiseTask/index.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    BuyManual: typeof import('./src/components/recharge/buyManual.vue')['default']
    BuyTokens: typeof import('./src/components/recharge/buyTokens.vue')['default']
    BuyUSDConfirm: typeof import('./src/components/recharge/buyUSDConfirm.vue')['default']
    Calculator: typeof import('./src/components/calculator/index.vue')['default']
    CandlestickChart: typeof import('./src/components/charts/CandlestickChart.vue')['default']
    Confirm: typeof import('./src/components/recharge/confirm.vue')['default']
    copy: typeof import('./src/components/recharge/index copy.vue')['default']
    CountDown: typeof import('./src/components/countDown/index.vue')['default']
    DoubleBenefit: typeof import('./src/components/modals/doubleBenefit.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    ManualTransfer: typeof import('./src/components/recharge/manualTransfer.vue')['default']
    Modals: typeof import('./src/components/modals/index.vue')['default']
    NewbieGuide: typeof import('./src/components/modals/newbieGuide.vue')['default']
    Recharge: typeof import('./src/components/recharge/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rules: typeof import('./src/components/rules/index.vue')['default']
    SendAmount: typeof import('./src/components/sendAmount/index.vue')['default']
    StopAmount: typeof import('./src/components/stopAmount/index.vue')['default']
    Toast: typeof import('./src/components/toast/index.vue')['default']
    TopToolbar: typeof import('./src/components/TopToolbar.vue')['default']
    WithdrawConfirm: typeof import('./src/components/withdrawConfirm/index.vue')['default']
  }
}
